"""
Hallucination Tracker for Bedrock Component Names.

This module tracks and measures hallucinated Bedrock component names
in conversion outputs. Hallucinated components are names that don't exist
in the actual Bedrock API but are generated by the LLM during conversion.

Based on issue #1189: The core problem with standard RAG for code translation
is that cosine similarity retrieves Bedrock API docs that LOOK similar to a
Java query but aren't the ones that produce valid Bedrock code.

This module helps measure:
1. Hallucination rate before UAE (baseline)
2. Hallucination rate after UAE fine-tuning
3. Reduction in hallucinated component names

Common hallucination patterns:
- Wrong component names: 'minecraft:custom.ai' instead of 'minecraft:behavior.custom_goal'
- Non-existent properties: 'minecraft:entity.custom_property'
- Incorrect event names: 'minecraft:on_custom_event' instead of 'minecraft:event.my_event'
"""

import json
import logging
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

logger = logging.getLogger(__name__)


KNOWN_VALID_COMPONENTS: Set[str] = {
    # AI/Behavior Components
    "minecraft:behavior.nearest_attackable",
    "minecraft:behavior.look_at_player",
    "minecraft:behavior.wander",
    "minecraft:behavior.float",
    "minecraft:behavior.custom_goal",
    "minecraft:behavior.move_to_goal",
    "minecraft:behavior.melee_attack",
    "minecraft:behavior.nearest_prioritized",
    "minecraft:behavior.stay_while_sitting",
    "minecraft:behavior.leap_at_target",
    "minecraft:behavior.mount_pathing",
    "minecraft:behavior.random_look_around",
    "minecraft:behavior.nearest_entity",
    "minecraft:behavior.move_through_village",
    "minecraft:behavior.offer_flower",
    "minecraft:behavior.tempt",
    "minecraft:behavior.take_flower",
    "minecraft:behavior.find_cover",
    "minecraft:behavior.avoid_entity",
    "minecraft:behavior.follow_parent",
    "minecraft:behavior.guardian_attack",
    "minecraft:behavior.hunt",
    "minecraft:behavior.silverfish_merge_with_block",
    "minecraft:behavior.silverfish_wake_up_friends",
    "minecraft:behavior.skeleton_ranged_attack",
    "minecraft:behavior.sheep_guard",
    "minecraft:behavior.strider_wander",
    "minecraft:behavior.llama_trade",
    "minecraft:behavior.turtle_go_to_water",
    "minecraft:behavior.turtle_random_dive",
    "minecraft:behavior.turtle_random_land",
    "minecraft:behavior.villager_breed",
    "minecraft:behavior.villager_validate_trade",
    "minecraft:behavior.villager_work",
    "minecraft:behavior.wolf_defend_owner",
    "minecraft:behavior.wolf_seduce",
    "minecraft:behavior.zombie_attack",
    "minecraft:behavior.cat_sleep_on_owner_bed",
    # Entity Components
    "minecraft:entity_definition_event",
    "minecraft:entity_event_response",
    "minecraft:identifier",
    "minecraft:family",
    "minecraft:collision_box",
    "minecraft:health",
    "minecraft:movement",
    "minecraft:movement.flying",
    "minecraft:navigation.generic",
    "minecraft:navigation.walk",
    "minecraft:navigation.swim",
    "minecraft:navigation.climb",
    "minecraft:navigation.float",
    "minecraft:geometry",
    "minecraft:render",
    "minecraft:loot",
    "minecraft:equipment",
    "minecraft:burnable",
    "minecraft:health",
    "minecraft:attack",
    "minecraft:spawn_rules",
    "minecraft:scale",
    "minecraft:pushable",
    "minecraft:knockback_resistance",
    "minecraft:flight_fall_distance",
    "minecraft:block_interact",
    "minecraft:interact",
    "minecraft:damage_sensor",
    "minecraft:fire_immune",
    "minecraft:flags",
    "minecraft:healable",
    "minecraft:hurt_on_condition",
    "minecraft:immune_to_Wither",
    "minecraft:indoor_patrol",
    "minecraft:instant_despawn",
    "minecraft:item_storage",
    "minecraft:leashable",
    "minecraft:looting_enchant",
    "minecraft:mark_variant",
    "minecraft:movement.basic",
    "minecraft:nameable",
    "minecraft:navigation.climb",
    "minecraft:out_of_control",
    "minecraft:peek",
    "minecraft:persistent",
    "minecraft:phone_owner",
    "minecraft:preferred_path",
    "minecraft:projectile",
    "minecraft:protected",
    "minecraft:rail_movement",
    "minecraft:ravager_capable",
    "minecraft:rideable",
    "minecraft:rotation",
    "minecraft:runner",
    "minecraft:scaffolding_climb",
    "minecraft:scale_by_age",
    "minecraft:security_lost",
    "minecraft:share_entities",
    "minecraft:spawn_egg_item",
    "minecraft:tameable",
    "minecraft:target_nearby_sensor",
    "minecraft:teleport",
    "minecraft:tick_world",
    "minecraft:timer",
    "minecraft:transition_animation",
    "minecraft:type_family",
    "minecraft:underwater_movement",
    "minecraft:variant",
    "minecraft:walk_animation_rate",
    "minecraft:wants_jockey",
    "minecraft:water_movement",
    # Block Components
    "minecraft:geometry",
    "minecraft:material_instances",
    "minecraft:light_emission",
    "minecraft:light_filter",
    "minecraft:loot",
    "minecraft:map_color",
    "minecraft:geometry.walkable_completion",
    "minecraft:destructible_by_entity",
    "minecraft:destructible_by_mining",
    "minecraft:placement_filter",
    "minecraft:prevent_mobile_ending",
    "minecraft:material_reduce_blocking",
    # Item Components
    "minecraft:icon",
    "minecraft:render_offsets",
    "minecraft:use_animation",
    "minecraft:use_duration",
    "minecraft:food",
    "minecraft:cooldown",
    "minecraft:chargeable",
    "minecraft:durability",
    "minecraft:enchantable",
    "minecraft:repairable",
    "minecraft:record",
    "minecraft:jukebox_playable",
    "minecraft:knockback",
    "minecraft:launcher",
    "minecraft:max_stack",
    "minecraft:projectile",
    "minecraft:seed_plantable",
    "minecraft:shooter",
    "minecraft:stacked_armor_data",
    "minecraft:tag",
    "minecraft:tool",
    "minecraft:wearable",
    # Events
    "minecraft:event.my_event",
    "minecraft:event.add",
    "minecraft:event.remove",
    "minecraft:event.trigger",
}

VALID_EVENTS: Set[str] = {
    "minecraft:event.my_event",
    "minecraft:event.add",
    "minecraft:event.remove",
    "minecraft:event.trigger",
}


@dataclass
class HallucinatedComponent:
    """A detected hallucinated component."""

    component_name: str
    line_number: int
    context: str
    confidence: float
    hallucination_type: str


@dataclass
class HallucinationReport:
    """Report of hallucination analysis."""

    total_components: int
    hallucinated_count: int
    hallucination_rate: float
    hallucinated_components: List[HallucinatedComponent]
    valid_components: List[str]
    timestamp: str
    source_file: Optional[str] = None


class BedrockComponentHallucinationTracker:
    """
    Tracks and detects hallucinated Bedrock component names.

    This tracker identifies component names that don't exist in the
    Bedrock API but were generated in conversion outputs.
    """

    COMPONENT_PATTERN = re.compile(r"['\"]?(minecraft:\w+(?:\.\w+)*)['\"]?")
    EVENT_PATTERN = re.compile(r"['\"]?event['\"]?\s*:\s*['\"]?(\w+)['\"]?")
    BEHAVIOR_GOAL_PATTERN = re.compile(r"['\"]?(\w+_goal)['\"]?")

    def __init__(self, valid_components: Optional[Set[str]] = None):
        self.valid_components = valid_components or KNOWN_VALID_COMPONENTS
        self._reports: List[HallucinationReport] = []
        self._hallucination_history: List[Dict[str, Any]] = []

    def extract_components_from_text(self, text: str) -> List[str]:
        """Extract all Bedrock component names from text."""
        matches = self.COMPONENT_PATTERN.findall(text)
        return list(set(matches))

    def extract_components_from_json(self, json_str: str) -> List[str]:
        """Extract components from JSON text."""
        components = []

        component_matches = self.COMPONENT_PATTERN.findall(json_str)
        components.extend(component_matches)

        try:
            data = json.loads(json_str)
            components.extend(self._extract_from_dict(data))
        except (json.JSONDecodeError, RecursionError):
            pass

        return list(set(components))

    def _extract_from_dict(self, data: Any) -> List[str]:
        """Recursively extract components from dict/list structures."""
        components = []

        if isinstance(data, dict):
            for key, value in data.items():
                if key in ("events", "event", "add", "remove"):
                    if isinstance(value, dict):
                        components.extend(value.keys())
                if isinstance(value, str):
                    if value.startswith("minecraft:"):
                        components.append(value)
                    elif self.COMPONENT_PATTERN.match(value):
                        components.append(value)
                else:
                    components.extend(self._extract_from_dict(value))
        elif isinstance(data, list):
            for item in data:
                components.extend(self._extract_from_dict(item))

        return components

    def is_valid_component(self, component_name: str) -> bool:
        """Check if a component name is valid in Bedrock API."""
        if component_name in self.valid_components:
            return True

        if component_name.startswith("minecraft:behavior."):
            return True

        if component_name.startswith("minecraft:event."):
            return True

        return False

    def detect_hallucinations(
        self,
        text: str,
        source_file: Optional[str] = None,
    ) -> HallucinationReport:
        """
        Detect hallucinated components in text.

        Args:
            text: Text to analyze (JSON, code, or mixed)
            source_file: Optional source file path for reporting

        Returns:
            HallucinationReport with findings
        """
        components = self.extract_components_from_json(text)

        hallucinated_components = []
        valid_components = []

        for i, line in enumerate(text.split("\n"), 1):
            line_components = self.extract_components_from_text(line)
            for comp in line_components:
                if not self.is_valid_component(comp):
                    hallucination_type = self._classify_hallucination(comp)
                    hallucinated_components.append(
                        HallucinatedComponent(
                            component_name=comp,
                            line_number=i,
                            context=line.strip()[:100],
                            confidence=self._calculate_confidence(comp),
                            hallucination_type=hallucination_type,
                        )
                    )
                else:
                    valid_components.append(comp)

        hallucinated_count = len(hallucinated_components)
        total_components = len(components) if components else 1
        hallucination_rate = hallucinated_count / total_components if total_components > 0 else 0.0

        report = HallucinationReport(
            total_components=total_components,
            hallucinated_count=hallucinated_count,
            hallucination_rate=hallucination_rate,
            hallucinated_components=hallucinated_components,
            valid_components=list(set(valid_components)),
            timestamp=datetime.now().isoformat(),
            source_file=source_file,
        )

        self._reports.append(report)

        return report

    def _classify_hallucination(self, component: str) -> str:
        """Classify the type of hallucination."""
        if "ai" in component.lower() or "goal" in component.lower():
            return "fake_behavior_component"
        if "custom" in component.lower() and "event" in component.lower():
            return "fake_event_name"
        if "property" in component.lower() or "attribute" in component.lower():
            return "fake_property"
        return "unknown_component"

    def _calculate_confidence(self, component: str) -> float:
        """Calculate confidence that a component is hallucinated."""
        confidence = 0.5

        if "fake" in component.lower() or "custom_ai" in component.lower():
            confidence = 0.95
        elif "non_existent" in component.lower():
            confidence = 0.99

        return confidence

    def compare_before_after(
        self,
        before_text: str,
        after_text: str,
        label_before: str = "baseline",
        label_after: str = "uae",
    ) -> Dict[str, Any]:
        """
        Compare hallucination rates before and after a change.

        Args:
            before_text: Text before change (e.g., baseline retrieval)
            after_text: Text after change (e.g., UAE retrieval)
            label_before: Label for before text
            label_after: Label for after text

        Returns:
            Comparison metrics
        """
        before_report = self.detect_hallucinations(before_text)
        after_report = self.detect_hallucinations(after_text)

        reduction = before_report.hallucination_rate - after_report.hallucination_rate

        return {
            "before": {
                "label": label_before,
                "hallucination_rate": before_report.hallucination_rate,
                "hallucinated_count": before_report.hallucinated_count,
                "total_components": before_report.total_components,
            },
            "after": {
                "label": label_after,
                "hallucination_rate": after_report.hallucination_rate,
                "hallucinated_count": after_report.hallucinated_count,
                "total_components": after_report.total_components,
            },
            "reduction": {
                "absolute": reduction,
                "percent": (reduction / before_report.hallucination_rate * 100)
                if before_report.hallucination_rate > 0
                else 0.0,
            },
        }

    def get_average_hallucination_rate(self) -> float:
        """Get average hallucination rate across all reports."""
        if not self._reports:
            return 0.0

        total_rate = sum(r.hallucination_rate for r in self._reports)
        return total_rate / len(self._reports)

    def get_history(self) -> List[Dict[str, Any]]:
        """Get hallucination history."""
        return [
            {
                "timestamp": r.timestamp,
                "hallucination_rate": r.hallucination_rate,
                "hallucinated_count": r.hallucinated_count,
                "source_file": r.source_file,
            }
            for r in self._reports
        ]

    def export_history(self, path: str) -> None:
        """Export hallucination history to JSON file."""
        data = {
            "history": self.get_history(),
            "summary": {
                "total_reports": len(self._reports),
                "average_hallucination_rate": self.get_average_hallucination_rate(),
            },
        }

        with open(path, "w") as f:
            json.dump(data, f, indent=2)

        logger.info(f"Exported hallucination history to {path}")

    def reset(self) -> None:
        """Reset all reports and history."""
        self._reports = []
        self._hallucination_history = []


def create_hallucination_tracker() -> BedrockComponentHallucinationTracker:
    """Factory function to create a hallucination tracker."""
    return BedrockComponentHallucinationTracker()
