/**
 * Terms of Service Page
 */

import React from 'react';
import styles from './DocumentationSimple.module.css';

export const TermsPage: React.FC = () => {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.subtitle}>
          Last updated:{' '}
          {new Date().toLocaleDateString('en-US', {
            month: 'long',
            day: 'numeric',
            year: 'numeric',
          })}
        </p>
      </header>

      <nav className={styles.navigation}>
        <a href="#acceptance" className={styles.navLink}>
          Acceptance
        </a>
        <a href="#use" className={styles.navLink}>
          Acceptable Use
        </a>
        <a href="#ip" className={styles.navLink}>
          Intellectual Property
        </a>
        <a href="#availability" className={styles.navLink}>
          Service Availability
        </a>
        <a href="#liability" className={styles.navLink}>
          Limitation of Liability
        </a>
        <a href="#termination" className={styles.navLink}>
          Account Termination
        </a>
      </nav>

      <section id="acceptance" className={styles.section}>
        <h2 className={styles.sectionTitle}>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Portkit (&quot;the Service&quot;), you agree to
          be bound by these Terms of Service (&quot;Terms&quot;). If you do not
          agree to these Terms, do not use the Service.
        </p>
        <p>
          Portkit is a SaaS platform that converts Minecraft Java Edition mods
          to Bedrock Edition add-ons. The Service is provided to you subject to
          these Terms and our Privacy Policy.
        </p>
      </section>

      <section id="use" className={styles.section}>
        <h2 className={styles.sectionTitle}>2. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>
            Upload or convert malicious files, malware, or any content intended
            to harm Minecraft servers or players
          </li>
          <li>
            Attempt to reverse engineer, decompile, or disassemble any part of
            the Service or its underlying technology
          </li>
          <li>
            Use the Service to infringe upon the intellectual property rights of
            others, including but not limited to copyright holders of Minecraft
            mods
          </li>
          <li>
            Upload content that is illegal, harmful, offensive, or violates any
            applicable laws or regulations
          </li>
          <li>
            Resell, redistribute, or charge others for access to the Service
            without our written permission
          </li>
          <li>
            Attempt to gain unauthorized access to any systems, networks, or
            data
          </li>
          <li>
            Use automated tools, bots, or scrapers to access the Service without
            prior written consent
          </li>
          <li>
            Upload files containing viruses, worms, or any other malicious code
          </li>
        </ul>
      </section>

      <section id="ip" className={styles.section}>
        <h2 className={styles.sectionTitle}>3. Intellectual Property</h2>
        <h3 className={styles.sectionTitle}>Your Content</h3>
        <p>
          You retain all rights to the mods and content you upload to ModPorter
          AI (&quot;Your Content&quot;). By uploading Your Content, you grant us
          a limited license to process it for the purpose of providing the
          Service.
        </p>
        <p>
          <strong>Portkit does not claim ownership of Your Content.</strong> We
          do not assert any ownership rights over the mods you convert.
        </p>
        <h3 className={styles.sectionTitle}>Service Content</h3>
        <p>
          The Service, including all software, designs, text, graphics, and
          other content (excluding Your Content), are owned by Portkit or its
          licensors and are protected by intellectual property laws.
        </p>
        <p>
          Conversion reports and outputs generated by the Service are provided
          for your personal use. You are responsible for ensuring you have the
          right to convert any mod you submit.
        </p>
      </section>

      <section id="conversion-authorization" className={styles.section}>
        <h2 className={styles.sectionTitle}>
          3a. Conversion Authorization Warranty
        </h2>
        <p>
          <strong>Important:</strong> Before converting any mod, you must have
          the legal right to do so. By submitting a mod for conversion, you
          represent and warrant that:
        </p>
        <ul>
          <li>You are the original author of the mod, OR</li>
          <li>
            You have received explicit written permission from the mod author to
            convert their mod to Bedrock Edition, OR
          </li>
          <li>
            The mod is licensed under a permissive license (MIT, Apache 2.0,
            BSD, CC0, GPL 3.0+, or Unlicense) that permits derivative works
          </li>
        </ul>
        <p>
          <strong>You agree to indemnify and hold harmless Portkit</strong> from
          any claims, damages, or expenses arising from unauthorized conversion
          of any mod you upload or convert using the Service.
        </p>
        <p>
          Portkit reserves the right to block conversion of mods that appear to
          use All Rights Reserved (ARR) or other restrictive licenses without
          verified authorization.
        </p>
      </section>

      <section id="dmca" className={styles.section}>
        <h2 className={styles.sectionTitle}>3b. DMCA Compliance</h2>
        <p>
          Portkit complies with the Digital Millennium Copyright Act (DMCA). If
          you believe your copyrighted work has been infringed on our Service,
          please contact our designated DMCA agent:
        </p>
        <p>
          <strong>Email:</strong> dmca@portkit.ai
        </p>
        <p>
          Upon receiving a valid DMCA takedown notice, we will remove the
          infringing content within 24 hours and notify the affected user. Users
          may submit a counter-notice if they believe their content was wrongly
          removed.
        </p>
      </section>

      <section id="availability" className={styles.section}>
        <h2 className={styles.sectionTitle}>4. Service Availability</h2>
        <h3 className={styles.sectionTitle}>Free and Paid Tiers</h3>
        <p>
          Free and paid tiers of the Service are provided &quot;as is&quot;
          without any service level agreement (SLA). We do not guarantee
          uninterrupted or error-free service availability for these tiers.
        </p>
        <h3 className={styles.sectionTitle}>Enterprise Tier</h3>
        <p>
          Enterprise tier subscribers are entitled to a 99.9% uptime SLA,
          excluding scheduled maintenance and circumstances beyond our control.
          Credits or refunds for downtime beyond this threshold are provided at
          our discretion.
        </p>
        <h3 className={styles.sectionTitle}>Maintenance</h3>
        <p>
          We may perform scheduled maintenance from time to time. We will make
          reasonable efforts to notify users in advance of any planned downtime.
        </p>
      </section>

      <section id="liability" className={styles.section}>
        <h2 className={styles.sectionTitle}>5. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, MODPORTER AI SHALL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
          PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
        </p>
        <ul>
          <li>Loss of profits, revenue, data, or business opportunities</li>
          <li>Loss or corruption of data resulting from use of the Service</li>
          <li>
            Any damages arising from reliance on the Service or its outputs
          </li>
          <li>Unauthorized access to your account or data</li>
        </ul>
        <p>
          OUR TOTAL LIABILITY ARISING FROM OR RELATED TO THE SERVICE SHALL NOT
          EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE
          CLAIM.
        </p>
        <p>
          Some jurisdictions do not allow the exclusion or limitation of
          liability for consequential damages, so the above limitations may not
          apply to you.
        </p>
      </section>

      <section id="termination" className={styles.section}>
        <h2 className={styles.sectionTitle}>6. Account Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account and access
          to the Service at any time, without prior notice, for:
        </p>
        <ul>
          <li>Violation of these Terms or our Acceptable Use policy</li>
          <li>Fraudulent or illegal activity</li>
          <li>Non-payment of fees (for paid tiers)</li>
          <li>Extended inactivity, at our discretion</li>
          <li>Requests by law enforcement or regulatory authorities</li>
        </ul>
        <p>
          You may cancel your account at any time by contacting support or using
          the account settings. Upon termination, your right to use the Service
          ceases immediately.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Contact Us</h2>
        <p>
          If you have any questions about these Terms of Service, please contact
          us at:
        </p>
        <p>
          <strong>Email:</strong> legal@portkit.cloud
          <br />
          <strong>Address:</strong> Portkit, [Address]
        </p>
      </section>
    </div>
  );
};

export default TermsPage;
